//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdilearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public Monster()
        {
            this.Quests = new HashSet<Quest>();
            this.PartyQuests = new HashSet<PartyQuest>();
        }
    
        public int MonsterID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DangerLevel { get; set; }
        public string Habitat { get; set; }
        public Nullable<int> RewardGold { get; set; }
        public Nullable<float> DifficultyMultiplier { get; set; }
    
        public virtual ICollection<Quest> Quests { get; set; }
        public virtual ICollection<PartyQuest> PartyQuests { get; set; }
    }
}
