//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdilearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMember
    {
        public int PartyMemberID { get; set; }
        public Nullable<int> PartyQuestID { get; set; }
        public Nullable<int> HunterID { get; set; }
        public Nullable<int> RewardEarned { get; set; }
    
        public virtual Hunter Hunter { get; set; }
        public virtual PartyQuest PartyQuest { get; set; }
    }
}
