//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdilearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyQuest
    {
        public PartyQuest()
        {
            this.TreasuryTransactions = new HashSet<TreasuryTransaction>();
            this.PartyMembers = new HashSet<PartyMember>();
        }
    
        public int PartyQuestID { get; set; }
        public string QuestCode { get; set; }
        public Nullable<int> MonsterID { get; set; }
        public Nullable<System.DateTime> HuntDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalReward { get; set; }
    
        public virtual Monster Monster { get; set; }
        public virtual ICollection<TreasuryTransaction> TreasuryTransactions { get; set; }
        public virtual ICollection<PartyMember> PartyMembers { get; set; }
    }
}
