//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdilearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public int QuestID { get; set; }
        public Nullable<int> HunterID { get; set; }
        public Nullable<int> MonsterID { get; set; }
        public Nullable<System.DateTime> HuntDate { get; set; }
        public string Result { get; set; }
        public Nullable<int> RewardEarned { get; set; }
        public string Status { get; set; }
        public string QuestCode { get; set; }
    
        public virtual Hunter Hunter { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
