//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdilearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> PartyQuestID { get; set; }
        public Nullable<int> TaxAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> QuestID { get; set; }
    
        public virtual PartyQuest PartyQuest { get; set; }
        public virtual Quest Quest { get; set; }
    }
}
